[project]
name = "todo-app-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.17.0",
    "fastapi[all]>=0.120.0",
    "passlib[bcrypt]>=1.7.4",
    "python-dotenv>=1.1.1",
]
